name: Deploy Staging

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          docker-compose build
      - name: Deploy to staging
        env:
          STAGING_SERVER: 3.0.16.137
          STAGING_USER: ubuntu
        run: |
          ssh -i ${{ secrets.STAGING_SERVER_KEY }} $STAGING_USER@$STAGING_SERVER "cd /var/www/seftu && git pull origin master && docker-compose stop seftu_web && docker-compose up -d"
          
